import { Poppins } from "next/font/google";
import "./globals.css";
// import Header from "./components/Header";
// import Footer from "./components/Footer";
import AuthProvider from "./self-components/AuthProvider";
import {session} from "next-auth/react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Choose required weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}`}
      >
        {/* <Header /> */}
        <AuthProvider session={session}>

        {children}

        </AuthProvider>

        {/* <Footer /> */}
      </body>
    </html>
  );
}
